name: schoolapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
#  agora_uikit: ^1.3.3
  zego_uikit_prebuilt_video_conference: ^2.2.10
  intl: ^0.17.0
  toast: ^0.3.0
  wakelock: ^0.6.2
  wakelock_windows: ^0.2.1
  file_picker: ^5.3.2
  flutter_pdfview: ^1.3.1
  path_provider: ^2.0.15
  flutter_cached_pdfview: ^0.4.1
  photo_view: ^0.14.0
  slide_countdown: ^0.6.0

dependency_overrides:
  win32: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
